language: python
python:
  - 2.7
install: 
  - pip install .
  - pip install -r tests/requirements.txt
  - pip install coveralls
services:
  - elasticsearch
script:
  - export ELASTIC_SEARCH_URL=localhost
  - python tests/manage.py test
  - coverage run --source=tests tests/manage.py test
after_success:
  coveralls
